---

parserOptions:
  ecmaVersion: 6

plugins:
  # https://github.com/jest-community/eslint-plugin-jest
  - jest

# https://eslint.org/docs/user-guide/configuring#specifying-environments
env:
  node: true
  es6: true

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'

rules:
    no-console: 0,
    import/extensions: 0